module.exports = {
  "name": "Avatar",
  "releaseStatus": "stable",
  "regions": [
    {
      "name": "iconSvg",
      "description": "Specifies the SVG of a custom icon.\nUse this property if the icon you want isn't available.\nIf you set both `iconUrl` and `iconSvg`, `iconSvg` will take precedence.\n",
      "isDefault": false
    }
  ],
  "functions": [],
  "properties": [
    {
      "name": "ariaLabel",
      "type": "string",
      "optional": false,
      "description": "Text to describe the avatar for assistive technology.\nWhen more than one avatar is used, provide a unique label for each.\nFor example, \"Avatar of John Doe\" or \"Avatar of generative AI assistant\".\nIf `tooltipText` is used make sure to include it in the `ariaLabel`.\n"
    },
    {
      "name": "color",
      "type": "string",
      "inlineType": {
        "name": "AvatarProps.Color",
        "type": "union",
        "values": [
          "default",
          "gen-ai"
        ]
      },
      "optional": true,
      "description": "Determines the color of the avatar.\nUse `gen-ai` for AI assistants and `default` otherwise.",
      "defaultValue": "\"default\""
    },
    {
      "name": "iconName",
      "type": "string",
      "inlineType": {
        "name": "IconProps.Name",
        "type": "union",
        "values": [
          "add-plus",
          "anchor-link",
          "angle-left-double",
          "angle-left",
          "angle-right-double",
          "angle-right",
          "angle-up",
          "angle-down",
          "arrow-left",
          "arrow-right",
          "audio-full",
          "audio-half",
          "audio-off",
          "bug",
          "call",
          "calendar",
          "caret-down-filled",
          "caret-down",
          "caret-left-filled",
          "caret-right-filled",
          "caret-up-filled",
          "caret-up",
          "check",
          "contact",
          "close",
          "copy",
          "delete-marker",
          "download",
          "drag-indicator",
          "edit",
          "ellipsis",
          "envelope",
          "expand",
          "external",
          "file-open",
          "file",
          "filter",
          "flag",
          "folder-open",
          "folder",
          "gen-ai",
          "group-active",
          "group",
          "heart",
          "heart-filled",
          "insert-row",
          "key",
          "keyboard",
          "lock-private",
          "menu",
          "microphone",
          "microphone-off",
          "multiscreen",
          "notification",
          "redo",
          "refresh",
          "remove",
          "resize-area",
          "script",
          "search",
          "security",
          "settings",
          "send",
          "share",
          "shrink",
          "star-filled",
          "star-half",
          "star",
          "status-in-progress",
          "status-info",
          "status-negative",
          "status-pending",
          "status-positive",
          "status-stopped",
          "status-warning",
          "subtract-minus",
          "suggestions",
          "thumbs-down-filled",
          "thumbs-down",
          "thumbs-up-filled",
          "thumbs-up",
          "ticket",
          "treeview-collapse",
          "treeview-expand",
          "undo",
          "unlocked",
          "upload-download",
          "upload",
          "user-profile-active",
          "user-profile",
          "video-off",
          "video-on",
          "video-unavailable",
          "view-full",
          "view-horizontal",
          "view-vertical",
          "zoom-in",
          "zoom-out",
          "zoom-to-fit"
        ]
      },
      "optional": true,
      "description": "Specifies the icon to be displayed as Avatar.\nUse `gen-ai` icon for AI assistants. By default `user-profile` icon is used.\nIf you set both `iconName` and `initials`, `initials` will take precedence.\n",
      "defaultValue": "\"user-profile\""
    },
    {
      "name": "iconUrl",
      "type": "string",
      "optional": true,
      "description": "Specifies the URL of a custom icon. Use this property if the icon you want isn't available, and your custom icon can't be an SVG.\nFor SVG icons, use the `iconSvg` slot instead.\nIf you set both `iconUrl` and `iconSvg`, `iconSvg` will take precedence.\n"
    },
    {
      "name": "initials",
      "type": "string",
      "optional": true,
      "description": "The text content shown directly in the avatar's body.\nCan be 1 or 2 symbols long, every subsequent symbol is ignored.\nUse it to define initials that uniquely identify the avatar's owner."
    },
    {
      "name": "loading",
      "type": "boolean",
      "optional": true,
      "description": "When set to true, a loading indicator is shown in avatar."
    },
    {
      "name": "tooltipText",
      "type": "string",
      "optional": true,
      "description": "The text content shown in the avatar's tooltip.\nWhen you use this property, make sure to include it in the `ariaLabel`.\n"
    }
  ],
  "events": []
};